### ISSUE TITLE
Any idea on the checkpoint file corruption?

### ISSUE THREAD

**Issue by Everloom-129** [wudongming97/RMOT#18]
As it can be seemed here:
```bash
root@tony:~/449_RMOT/exps/default$ ls
checkpoint0099.pth
root@tony:~/449_RMOT/exps/default$ cdd
root@tony:~/449_RMOT$ sh configs/r50_rmot_test.sh 
Training with Extra Self Attention in Every Decoder.
Training with Self-Cross Attention.
Namespace(accurate_ratio=False, append_crowd=False, aux_loss=True, backbone='resnet50', batch_size=1, bbox_loss_coef=5, cache_mode=False, cj=False, clip_max_norm=0.1, cls_loss_coef=2, coco_panoptic_path=None, coco_path='/data/workspace/detectron2/datasets/coco/', crop=False, data_txt_path_train='./datasets/data_path/refer-kitti.train', dataset_file='e2e_rmot', dec_layers=6, dec_n_points=4, decoder_cross_self=False, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=1024, dropout=0.0, enable_fpn=False, enc_layers=6, enc_n_points=4, epochs=200, eval=False, exp_name='submit', extra_track_attn=True, filter_ignore=False, focal_alpha=0.25, fp_ratio=0.3, frozen_weights=None, giou_loss_coef=2, gt_file_train=None, gt_file_val=None, hidden_dim=256, img_path='data/valid/JPEGImages/', input_video='figs/demo.mp4', loss_normalizer=False, lr=0.0002, lr_backbone=2e-05, lr_backbone_names=['backbone.0'], lr_drop=100, lr_drop_epochs=None, lr_linear_proj_mult=0.1, lr_linear_proj_names=['reference_points', 'sampling_offsets'], mask_loss_coef=1, masks=False, max_size=1333, memory_bank_len=4, memory_bank_score_thresh=0.0, memory_bank_type=None, memory_bank_with_self_attn=False, merger_dropout=0.0, meta_arch='rmot', mix_match=False, nheads=8, num_anchors=1, num_feature_levels=4, num_queries=300, num_workers=2, output_dir='exps/default', position_embedding='sine', position_embedding_scale=6.283185307179586, pretrained=None, query_interaction_layer='QIM', random_drop=0.1, refer_loss_coef=2, remove_difficult=False, resume='exps/default/checkpoint0099.pth', rmot_path='/data/Dataset/refer-kitti', sample_interval=1, sample_mode='random_interval', sampler_lengths=[2, 3, 4, 5], sampler_steps=[50, 90, 150], save_period=50, seed=42, set_cost_bbox=5, set_cost_class=2, set_cost_giou=2, set_cost_refer=2, sgd=False, sigmoid_attn=False, start_epoch=0, two_stage=False, update_query_pos=True, use_checkpoint=False, val_width=800, vis=False, visualization=True, weight_decay=0.0001, with_box_refine=True)
Traceback (most recent call last):
  File "inference.py", line 547, in <module>
    checkpoint = torch.load(args.resume, map_location='cpu')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
root@tony:~/449_RMOT$ 

explain where is wrong, which py file should I look into
```

I have config the checkpoint and run the code, but the checkpoint file seem to be buggy, does anyone know the possible behavior causing this? Thanks!

**Comment by Everloom-129** [comment]
There are many many many 'does not fully load the pre-trained weight' bug, does anyone know what cause this?
```
...
No param transformer.decoder.layers.4.update_attn.in_proj_weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.4.update_attn.in_proj_bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.4.update_attn.out_proj.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.4.update_attn.out_proj.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.4.norm4.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.4.norm4.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.update_attn.in_proj_weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.update_attn.in_proj_bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.update_attn.out_proj.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.update_attn.out_proj.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.norm4.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
No param transformer.decoder.layers.5.norm4.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Evaluating seq ['0005', 'black-cars-in-the-left.json']
Results are saved into exps/default/results_epoch99/0005/black-cars-in-the-left
  0%|                                                                                                                                                    | 0/297 [00:00<?, ?it/s]/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 297/297 [00:40<00:00,  7.41it/s]
save gt to exps/default/results_epoch99/0005/black-cars-in-the-left/gt.txt
totally 223 dts 0 occlusion dts
Evaluating seq ['0005', 'black-vehicles-in-the-left.json']
Results are saved into exps/default/results_epoch99/0005/black-vehicles-in-the-left
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████
```

**Comment by XuZiGuo-bit** [comment]
I met same problem , do you solve it?

**Comment by Everloom-129** [comment]
In my previous experiments, I remember it is fine and not cause problem to the program

**Comment by rishabh-akridata** [comment]
@Everloom-129 @XuZiGuo-bit, 
I am facing the same problem, did you manage to solve this issue?

Thanks.
