### ISSUE TITLE
MultiScaleDeformableAttention 

### ISSUE THREAD

**Issue by LHYUNMIN** [wudongming97/RMOT#24]
I am currently using a single 3090ti with CUDA 11.3, Python 3.8, torch==1.10.0+cu111, and torchvision==0.11. However, when I run training, I encounter an error, so I comment out the problematic section.
`import torchvision
if float(torchvision.__version__[:3]) < 0.5:
    import math
    from torchvision.ops.misc import _NewEmptyTensorOp
    def _check_size_scale_factor(dim, size, scale_factor):
        # type: (int, Optional[List[int]], Optional[float]) -> None
        if size is None and scale_factor is None:
            raise ValueError("either size or scale_factor should be defined")
        if size is not None and scale_factor is not None:
            raise ValueError("only one of size or scale_factor should be defined")
        if not (scale_factor is not None and len(scale_factor) != dim):
            raise ValueError(
                "scale_factor shape must match input shape. "
                "Input is {}D, scale_factor size is {}".format(dim, len(scale_factor))
            )
    def _output_size(dim, input, size, scale_factor):
        # type: (int, Tensor, Optional[List[int]], Optional[float]) -> List[int]
        assert dim == 2
        _check_size_scale_factor(dim, size, scale_factor)
        if size is not None:
            return size
        # if dim is not 2 or scale_factor is iterable use _ntuple instead of concat
        assert scale_factor is not None and isinstance(scale_factor, (int, float))
        scale_factors = [scale_factor, scale_factor]
        # math.floor might return float in py2.7
        return [
            int(math.floor(input.size(i + 2) * scale_factors[i])) for i in range(dim)
        ]
elif float(torchvision.__version__[:3]) < 0.7:
    from torchvision.ops import _new_empty_tensor
    from torchvision.ops.misc import _output_size`

After doing so, I continue to receive errors during training. 

`and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions   warnings.warn(
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    import datasets
  File "/home/ipis/rmot/RMOT/datasets/__init__.py", line 15, in <module>
    from .detmot import build as build_e2e_mot
  File "/home/ipis/rmot/RMOT/datasets/detmot.py", line 23, in <module>
    from models.structures import Instances
  File "/home/ipis/rmot/RMOT/models/__init__.py", line 10, in <module>
    from .deformable_detr import build as build_deformable_detr
  File "/home/ipis/rmot/RMOT/models/deformable_detr.py", line 29, in <module>
    from .deformable_transformer import build_deforamble_transformer
  File "/home/ipis/rmot/RMOT/models/deformable_transformer.py", line 25, in <module>
    from models.ops.modules import MSDeformAttn
  File "/home/ipis/rmot/RMOT/models/ops/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/ipis/rmot/RMOT/models/ops/modules/ms_deform_attn.py", line 24, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/ipis/rmot/RMOT/models/ops/functions/__init__.py", line 12, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/ipis/rmot/RMOT/models/ops/functions/ms_deform_attn_func.py", line 21, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'`

Could you help me understand why these errors are occurring and specify the exact versions I should be using?

**Comment by wudongming97** [comment]
You need to build MultiScaleDeformableAttention. Please see MOTR for this building: https://github.com/megvii-research/MOTR

**Comment by LHYUNMIN** [comment]
After installing transformers and torchtext using pip install transformers and pip install torchtext, the following error occurs when running the training:


`  ImportError: /home/ipis/anaconda3/envs/rmot/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE'`

**Comment by LHYUNMIN** [comment]
ubuntu20.04  cuda 11.4  gpu=3090ti
learning process

1. conda create -n deformable_detr python=3.8
2. conda activate deformable_detr
3. pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

4. pip install -r requirements.txt

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> optuna 3.3.0 requires PyYAML, which is not installed.
> ultralytics 8.0.201 requires pyyaml>=5.3.1, which is not installed.
> ultralytics 8.0.201 requires requests>=2.23.0, which is not installed.
> yolox 0.3.0 requires ninja, which is not installed.
> yolox 0.3.0 requires onnx==1.8.1, which is not installed.
> yolox 0.3.0 requires onnx-simplifier==0.3.5, which is not installed.
> yolox 0.3.0 requires onnxruntime==1.8.0, which is not installed.
> yolox 0.3.0 requires scikit-image, which is not installed.
> yolox 0.3.0 requires tensorboard, which is not installed.
> ultralytics 8.0.201 requires torch>=1.8.0, but you have torch 1.5.1 which is incompatible.
> ultralytics 8.0.201 requires torchvision>=0.9.0, but you have torchvision 0.6.0a0+35d732a which is incompatible.
> yolox 0.3.0 requires torch>=1.7, but you have torch 1.5.1 which is incompatible.
> Successfully installed contourpy-1.1.1 cycler-0.12.1 fonttools-4.54.1 kiwisolver-1.4.7 lap-0.4.0 matplotlib-3.7.5 motmetrics-1.4.0 opencv-python-4.10.0.84 packaging-24.1 pycocotools-2.0.7 pyparsing-3.1.4 scipy-1.10.1 tqdm-4.67.0 xmltodict-0.14.2

5. cd ./models/ops
6.sh ./make.sh
> running build
> running build_py
> running build_ext
> /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.8). Most likely this shouldn't be a problem.
>   warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
> running install
> /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> 
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` directly.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>         ********************************************************************************
> 
> 
>   self.initialize_options()
> /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` and ``easy_install``.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://github.com/pypa/setuptools/issues/917 for details.
>         ********************************************************************************
> 
> 
>   self.initialize_options()
> running bdist_egg
> running egg_info
> writing MultiScaleDeformableAttention.egg-info/PKG-INFO
> writing dependency_links to MultiScaleDeformableAttention.egg-info/dependency_links.txt
> writing top-level names to MultiScaleDeformableAttention.egg-info/top_level.txt
> reading manifest file 'MultiScaleDeformableAttention.egg-info/SOURCES.txt'
> writing manifest file 'MultiScaleDeformableAttention.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/modules
> copying build/lib.linux-x86_64-cpython-38/modules/__init__.py -> build/bdist.linux-x86_64/egg/modules
> copying build/lib.linux-x86_64-cpython-38/modules/ms_deform_attn.py -> build/bdist.linux-x86_64/egg/modules
> copying build/lib.linux-x86_64-cpython-38/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/functions
> copying build/lib.linux-x86_64-cpython-38/functions/__init__.py -> build/bdist.linux-x86_64/egg/functions
> copying build/lib.linux-x86_64-cpython-38/functions/ms_deform_attn_func.py -> build/bdist.linux-x86_64/egg/functions
> byte-compiling build/bdist.linux-x86_64/egg/modules/__init__.py to __init__.cpython-38.pyc
> byte-compiling build/bdist.linux-x86_64/egg/modules/ms_deform_attn.py to ms_deform_attn.cpython-38.pyc
> byte-compiling build/bdist.linux-x86_64/egg/functions/__init__.py to __init__.cpython-38.pyc
> byte-compiling build/bdist.linux-x86_64/egg/functions/ms_deform_attn_func.py to ms_deform_attn_func.cpython-38.pyc
> creating stub loader for MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/MultiScaleDeformableAttention.py to MultiScaleDeformableAttention.cpython-38.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying MultiScaleDeformableAttention.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying MultiScaleDeformableAttention.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying MultiScaleDeformableAttention.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying MultiScaleDeformableAttention.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> __pycache__.MultiScaleDeformableAttention.cpython-38: module references __file__
> creating 'dist/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> creating /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> Extracting MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg to /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages
> Adding MultiScaleDeformableAttention 1.0 to easy-install.pth file
> 
> Installed /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> Processing dependencies for MultiScaleDeformableAttention==1.0
> Finished processing dependencies for MultiScaleDeformableAttention==1.0

**
7. sh configs/r50_rmot_train.sh

> import MultiScaleDeformableAttention as MSDA
> ImportError: /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

I've been trying to run the process in this sequence, but the training process is very difficult. Could you please provide advice on whether there might be an issue with the sequence?

**Comment by zyn213** [comment]
Hi, it looks like you didn't successfully install the required dependencies in requirements.txt. By the way, the log indicates a CUDA version mismatch with your installed PyTorch; you might have PyTorch at a higher version than needed.

**Comment by XuZiGuo-bit** [comment]
> ubuntu20.04 cuda 11.4 gpu=3090ti learning process
> 
> 1. conda create -n deformable_detr python=3.8
> 2. conda activate deformable_detr
> 3. pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
> 4. pip install -r requirements.txt
> 
> > ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> > optuna 3.3.0 requires PyYAML, which is not installed.
> > ultralytics 8.0.201 requires pyyaml>=5.3.1, which is not installed.
> > ultralytics 8.0.201 requires requests>=2.23.0, which is not installed.
> > yolox 0.3.0 requires ninja, which is not installed.
> > yolox 0.3.0 requires onnx==1.8.1, which is not installed.
> > yolox 0.3.0 requires onnx-simplifier==0.3.5, which is not installed.
> > yolox 0.3.0 requires onnxruntime==1.8.0, which is not installed.
> > yolox 0.3.0 requires scikit-image, which is not installed.
> > yolox 0.3.0 requires tensorboard, which is not installed.
> > ultralytics 8.0.201 requires torch>=1.8.0, but you have torch 1.5.1 which is incompatible.
> > ultralytics 8.0.201 requires torchvision>=0.9.0, but you have torchvision 0.6.0a0+35d732a which is incompatible.
> > yolox 0.3.0 requires torch>=1.7, but you have torch 1.5.1 which is incompatible.
> > Successfully installed contourpy-1.1.1 cycler-0.12.1 fonttools-4.54.1 kiwisolver-1.4.7 lap-0.4.0 matplotlib-3.7.5 motmetrics-1.4.0 opencv-python-4.10.0.84 packaging-24.1 pycocotools-2.0.7 pyparsing-3.1.4 scipy-1.10.1 tqdm-4.67.0 xmltodict-0.14.2
> 
> 5. cd ./models/ops
>    6.sh ./make.sh
> 
> > running build
> > running build_py
> > running build_ext
> > /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
> > warnings.warn(msg.format('we could not find ninja.'))
> > /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.8). Most likely this shouldn't be a problem.
> > warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
> > running install
> > /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> > ```
> >     ********************************************************************************
> >     Please avoid running ``setup.py`` directly.
> >     Instead, use pypa/build, pypa/installer or other
> >     standards-based tools.
> > 
> >     See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
> >     ********************************************************************************
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > self.initialize_options()
> > /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
> > !!
> > ```
> >     ********************************************************************************
> >     Please avoid running ``setup.py`` and ``easy_install``.
> >     Instead, use pypa/build, pypa/installer or other
> >     standards-based tools.
> > 
> >     See https://github.com/pypa/setuptools/issues/917 for details.
> >     ********************************************************************************
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > self.initialize_options()
> > running bdist_egg
> > running egg_info
> > writing MultiScaleDeformableAttention.egg-info/PKG-INFO
> > writing dependency_links to MultiScaleDeformableAttention.egg-info/dependency_links.txt
> > writing top-level names to MultiScaleDeformableAttention.egg-info/top_level.txt
> > reading manifest file 'MultiScaleDeformableAttention.egg-info/SOURCES.txt'
> > writing manifest file 'MultiScaleDeformableAttention.egg-info/SOURCES.txt'
> > installing library code to build/bdist.linux-x86_64/egg
> > running install_lib
> > creating build/bdist.linux-x86_64
> > creating build/bdist.linux-x86_64/egg
> > creating build/bdist.linux-x86_64/egg/modules
> > copying build/lib.linux-x86_64-cpython-38/modules/**init**.py -> build/bdist.linux-x86_64/egg/modules
> > copying build/lib.linux-x86_64-cpython-38/modules/ms_deform_attn.py -> build/bdist.linux-x86_64/egg/modules
> > copying build/lib.linux-x86_64-cpython-38/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
> > creating build/bdist.linux-x86_64/egg/functions
> > copying build/lib.linux-x86_64-cpython-38/functions/**init**.py -> build/bdist.linux-x86_64/egg/functions
> > copying build/lib.linux-x86_64-cpython-38/functions/ms_deform_attn_func.py -> build/bdist.linux-x86_64/egg/functions
> > byte-compiling build/bdist.linux-x86_64/egg/modules/**init**.py to **init**.cpython-38.pyc
> > byte-compiling build/bdist.linux-x86_64/egg/modules/ms_deform_attn.py to ms_deform_attn.cpython-38.pyc
> > byte-compiling build/bdist.linux-x86_64/egg/functions/**init**.py to **init**.cpython-38.pyc
> > byte-compiling build/bdist.linux-x86_64/egg/functions/ms_deform_attn_func.py to ms_deform_attn_func.cpython-38.pyc
> > creating stub loader for MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so
> > byte-compiling build/bdist.linux-x86_64/egg/MultiScaleDeformableAttention.py to MultiScaleDeformableAttention.cpython-38.pyc
> > creating build/bdist.linux-x86_64/egg/EGG-INFO
> > copying MultiScaleDeformableAttention.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> > copying MultiScaleDeformableAttention.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> > copying MultiScaleDeformableAttention.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> > copying MultiScaleDeformableAttention.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> > writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> > zip_safe flag not set; analyzing archive contents...
> > **pycache**.MultiScaleDeformableAttention.cpython-38: module references **file**
> > creating 'dist/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> > removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> > Processing MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> > creating /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> > Extracting MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg to /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages
> > Adding MultiScaleDeformableAttention 1.0 to easy-install.pth file
> > Installed /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg
> > Processing dependencies for MultiScaleDeformableAttention==1.0
> > Finished processing dependencies for MultiScaleDeformableAttention==1.0
> 
> ** 7. sh configs/r50_rmot_train.sh
> 
> > import MultiScaleDeformableAttention as MSDA
> > ImportError: /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> 
> I've been trying to run the process in this sequence, but the training process is very difficult. Could you please provide advice on whether there might be an issue with the sequence?

hello，when i  try to test the proces, same erro occured。Do you resolve it？
![image](https://github.com/user-attachments/assets/16da6fac-b3e4-4854-9b69-0d17a9f0e5bf)

**Comment by LHYUNMIN** [comment]
> > ubuntu20.04 cuda 11.4 gpu=3090ti 학습 과정
> > 
> > 1. conda create - 변형 가능_detr python=3.8
> > 2. conda는 변형 가능_detr을 활성화합니다
> > 3. pip torch 설치==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --추가-인덱스-url https://download.pytorch.org/whl/cu113
> > 4. pip 설치 -r 요구사항.txt
> > 
> > > : pip의 힘찬 대응은 현재로서는 모든 용기를 고려하지 않습니다. 이 행동은 다음 베이징 충돌의 원인입니다. 
> > > optuna 3.3.0에는 설치되지 않은 PyYAML이 필요합니다. 
> > > ultralytics 8.0.201에는 설치되지 않은 pyyaml>=5.3.1이 필요합니다. 
> > > ultralytics 8.0.201에는 설치되지 않은 요청>=2.23.0이 필요합니다. 
> > > yolox 0.3.0에는 설치되지 않은 닌자가 필요합니다. 
> > > yolox 0.3.0에는 설치되지 않은 onnx==1.8.1이 필요합니다. 
> > > yolox 0.3.0에는 설치되지 않은 onnx-simplifier==0.3.5가 필요합니다. 
> > > yolox 0.3.0에는 설치되지 않은 onnxruntime==1.8.0이 필요합니다. 
> > > yolox 0.3.0에는 설치되지 않은 scikit-image가 필요합니다. 
> > > yolox 0.3.0에는 tensorboard가 꼭 필요하지만 설치되어 있지 않습니다. 
> > > ultralytics 8.0.201에는 torch>=1.8.0이 필요하지만 호환되지 않는 torch 1.5.1이 있습니다. 
> > > ultralytics 8.0.201에는 torchvision>=0.9.0이 필요하지만 호환되지 않는 torchvision 0.6.0a0+35d732a가 있습니다. 
> > > yolox 0.3.0에는 torch>=1.7이 필요하지만 호환되지 않는 torch 1.5.1이 있습니다. 
> > > Contourpy-1.1.1 Cycler-0.12.1 Fonttools-4.54.1 kiwisolver-1.4.7 lap-0.4.0 matplotlib-3.7.5 motmetrics-1.4.0 opencv-python-4.10.0.84 Packaging-24.1 pycocotools-2.0.7 파이파싱-3.1.4 scipy-1.10.1 tqdm-4.67.0 xmltodict-0.14.2를 성공으로 설치했습니다.
> > 
> > 
> > 
> > 5. cd ./models/ops 
> >    6.sh ./make.sh
> > 
> > > 실행 빌드 
> > > 실행 build_py 
> > > 실행 build_ext 
> > > /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: ninja를 BuildExtension 백엔드로 사용하려고 ninja를 찾기 수 없습니다. 승리 distutils 백엔드를 사용하는 것으로 돌아갑니다. 
> > > warnings.warn(msg.format('ninja를 찾을 수 없습니다.')) 
> > > /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/torch/utils/cpp_extension.py:414: UserWarning : 감지된 CUDA 버전(11.4)에는 PyTorch(11.8)을 사용하는 데 사용되는 버전과 일부 버전이 일치하지 않습니다. 아마도 문제가 없을 것입니다. 
> > > warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda)) 
> > > install 
> > > /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66 실행: SetuptoolsDeprecationWarning: setup .py install이 더 이상 사용되지 않습니다.
> > > ```
> > >     ********************************************************************************
> > >     Please avoid running ``setup.py`` directly.
> > >     Instead, use pypa/build, pypa/installer or other
> > >     standards-based tools.
> > > 
> > >     See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
> > >     ********************************************************************************
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > self.initialize_options() 
> > > /home/ipis/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install 시리즈는 더 이상 사용하지 않습니다. 
> > > !!
> > > ```
> > >     ********************************************************************************
> > >     Please avoid running ``setup.py`` and ``easy_install``.
> > >     Instead, use pypa/build, pypa/installer or other
> > >     standards-based tools.
> > > 
> > >     See https://github.com/pypa/setuptools/issues/917 for details.
> > >     ********************************************************************************
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > self.initialize_options() 
> > > 실행 bdist_egg 
> > > 실행 egg_info 
> > > 작성 MultiScaleDeformableAttention.egg-info/PKG-INFO 
> > > 작성 MultiScaleDeformableAttention.egg-info/dependent_links.txt에 대한 dependency_links 
> > > 작성 MultiScaleDeformableAttention.egg-info/top_level.txt에 대한 토론 이름 작성 
> > > 매니페스트 파일 'MultiScaleDeformableAttention.egg-info/SOURCES.txt' 읽기 
> > > 매니페스트 파일 'MultiScaleDeformableAttention.egg-info/SOURCES.txt' 
> > > 작성 라이브러리 코드 build/bdist.linux-x86_64/egg 
> > > 설치 install_lib 
> > > 실행 build/bdist.linux-x86_64 
> > > 생성 build/ bdist.linux-x86_64/egg 
> > > 생성 build/bdist.linux-x86_64/egg/modules 
> > > 생성 사본 build/lib.linux-x86_64-cpython-38/modules/ **init** .py -> build/bdist.linux 
> > > -x86_64/egg/modules 복사 build/lib.linux-x86_64-cpython-38/modules/ms_deform_attn.py -> build/bdist.linux-x86_64/egg/modules 
> > > 복사 build/lib.linux-x86_64-cpython-38/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg 
> > > 생성 build /bdist.linux-x86_64/egg/functions 
> > > 복사 build/lib.linux-x86_64-cpython-38/functions/ **init** .py -> build/bdist.linux-x86_64/egg/functions 
> > > 복사 build/lib.linux-x86_64-cpython-38/functions/ms_deform_attn_func.py -> build/bdist.linux-x86_64/egg/functions 
> > > 바이트 build/bdist.linux- x86_64/egg/modules/ **init** .py를 **init** .cpython-38.pyc 
> > > 로 바이트 바이트 build/bdist.linux-x86_64/egg/modules/ms_deform_attn.py를 ms_deform_attn.cpython-38.pyc로 바이트 바이트 
> > > build/bdist.linux-x86_64/egg/functions/ **init** .py 를 **init** .cpython-38.pyc 로 
> > > 바이트 내부 build/bdist.linux-x86_64/egg/functions/ms_deform_attn_func.py를 ms_deform_attn_func.cpython-38.pyc로 
> > > 만들기 MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so에 대한 스텟 로더를 배치 
> > > . build/bdist.linux-x86_64/egg/MultiScaleDeformableAttention.py를 MultiScaleDeformableAttention.cpython-38.pyc로 바이트를 띄웁니다. 
> > > build/bdist.linux-x86_64/egg/EGG-INFO를 생성 
> > > MultiScaleDeformableAttention.egg-info/PKG-INFO를 복사합니다 -> build/bdist.linux-x86_64/egg /EGG-INFO 
> > > 를 생성 MultiScaleDeformableAttention.egg-info/ SOURCES.txt를 복사합니다 -> build/bdist.linux-x86_64/egg/EGG-INFO를 
> > > MultiScaleDeformableAttention.egg-info/dependent_links.txt -> 
> > > build/bdist.linux-x86_64/egg/EGG-INFO로 MultiScaleDeformableAttention.egg-info/top_level.txt - > 빌드/bdist.linux-x86_64/egg/EGG-INFO 
> > > 로 복사 build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt 
> > > zip_safe 선언을 설정했다고 합니다. 저장 내용 분석 중... 
> > > **pycache** .MultiScaleDeformableAttention.cpython-38: 모듈 참조 **파일** 
> > > 'dist/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg' 생성 및 'build/bdist.linux-x86_64/egg' 추가 
> > > 'build/bdist.linux-x86_64/egg'(및 그 아래 모든 항목) 제거 
> > > MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg 
> > > 처리 /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg 
> > > MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg 추출 생성 /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages 
> > > easy-install.pth 파일에 MultiScaleDeformableAttention 1.0 추가 
> > > /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg 설치 
> > > MultiScaleDeformableAttention==1.0에 대한 응원성 처리 
> > > MultiScaleDeformableAttention==1.0에 대한 추진력 강화
> > 
> > 
> > ** 7. sh 구성/r50_rmot_train.sh
> > > MultiScaleDeformableAttention을 MSDA ImportError로 가져오기 
> > > : /home/ipis/anaconda3/envs/rmot/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-38-x86_64 -linux -gnu.so: 정의되지 않음 기호: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8선택적INS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> > 
> > 
> > 저는 이 관계에서 프로세스를 실행하는 데 중점을 두고 있으며, 훈련 프로세스가 매우 불편합니다. 서로에 대한 문제가 있는지를 좋아하는가?
> 
> 안녕하세요, 프로세스를 시도하려고 시도했을 때 동일한 오류가 발생했습니다. 치료하셨나요? ![영상](https://private-user-images.githubusercontent.com/160221618/389549686-16da6fac-b3e4-4854-9b69-0d17a9f0e5bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDUyMDUsIm5iZiI6MTczMjYwNDkwNSwicGF0aCI6Ii8xNjAyMjE2MTgvMzg5NTQ5Njg2LTE2ZGE2ZmFjLWIzZTQtNDg1NC05YjY5LTBkMTdhOWYwZTViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNzA4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTBjN2NmM2FkZDczNzUyNDA1MjM0MTAyMWVmZjFhOGNiNDE5MDc3MmVkNmVkM2EzNzM0OWQ5YWE1NmIyZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hIk0XUTM_cILABdZ9g7WUL_2-sPFik_p8NMJ6FpK-Fg)


hello,

You need to first visit the MOTR GitHub repository and run the initial version.

thank you

**Comment by XuZiGuo-bit** [comment]
thank you for your answer!
